In [1]:
import torch.nn as nn
import torch

### Random embedding

In [3]:
embedding = nn.Embedding(10,3)

In [4]:
embedding

Embedding(10, 3)

In [5]:
embedding.weight

Parameter containing:
tensor([[ 1.6934,  1.7323, -0.2495],
        [-0.6647,  0.6464, -0.0640],
        [ 1.1118, -1.1743,  0.2685],
        [-0.0335, -0.1774,  1.1351],
        [ 0.1263,  0.1018,  1.1946],
        [ 1.0600,  0.3789,  0.1963],
        [ 1.1849, -1.4400, -0.6275],
        [ 1.3810, -0.2324, -0.8808],
        [ 2.4278,  0.0407,  1.3464],
        [ 0.8789,  0.2496,  0.9578]], requires_grad=True)

In [6]:
input = torch.LongTensor([[1,2,4,5],[4,3,2,9]])

In [7]:
input

tensor([[1, 2, 4, 5],
        [4, 3, 2, 9]])

In [8]:
embedding(input)

tensor([[[-0.6647,  0.6464, -0.0640],
         [ 1.1118, -1.1743,  0.2685],
         [ 0.1263,  0.1018,  1.1946],
         [ 1.0600,  0.3789,  0.1963]],

        [[ 0.1263,  0.1018,  1.1946],
         [-0.0335, -0.1774,  1.1351],
         [ 1.1118, -1.1743,  0.2685],
         [ 0.8789,  0.2496,  0.9578]]], grad_fn=<EmbeddingBackward>)

In [9]:
embedding(input).shape

torch.Size([2, 4, 3])

### pretrained

In [10]:
ptrain_emb = nn.Embedding.from_pretrained(
    torch.FloatTensor([[1,2,3],[3,3,3]]))

In [11]:
ptrain_emb

Embedding(2, 3)

In [12]:
ptrain_emb(torch.LongTensor([0]))

tensor([[1., 2., 3.]])

### EmbeddingBag and offsets
input is 1D of shape (N), it will be treated as a concatenation of multiple bags (sequences).
offsets is required to be a 1D tensor containing the starting index positions of each bag in input. Therefore, for offsets of shape (B), input will be viewed as having B bags

In [16]:
embedding_sum = nn.EmbeddingBag.from_pretrained(
    embedding.weight, mode="max")

In [17]:
embedding_sum.weight

Parameter containing:
tensor([[ 1.6934,  1.7323, -0.2495],
        [-0.6647,  0.6464, -0.0640],
        [ 1.1118, -1.1743,  0.2685],
        [-0.0335, -0.1774,  1.1351],
        [ 0.1263,  0.1018,  1.1946],
        [ 1.0600,  0.3789,  0.1963],
        [ 1.1849, -1.4400, -0.6275],
        [ 1.3810, -0.2324, -0.8808],
        [ 2.4278,  0.0407,  1.3464],
        [ 0.8789,  0.2496,  0.9578]])

In [28]:
input = torch.LongTensor([0,1,2,3,4,5])
offsets = torch.LongTensor([0,1])

In [29]:
embedding_sum(input, offsets)

tensor([[ 1.6934,  1.7323, -0.2495],
        [ 1.1118,  0.6464,  1.1946]])