In [1]:
import numpy as np

In [26]:
A = np.arange(6).reshape(2,3)

In [27]:
A

array([[0, 1, 2],
       [3, 4, 5]])

In [28]:
A.reshape(1, 6)

array([[0, 1, 2, 3, 4, 5]])

In [29]:
A.reshape(-1)

array([0, 1, 2, 3, 4, 5])

In [34]:
A.reshape(6,-1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [36]:
A.reshape(3, -1)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [46]:
B = np.arange(60).reshape(10,3,2)

In [47]:
B

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35]],

       [[36, 37],
        [38, 39],
        [40, 41]],

       [[42, 43],
        [44, 45],
        [46, 47]],

       [[48, 49],
        [50, 51],
        [52, 53]],

       [[54, 55],
        [56, 57],
        [58, 59]]])

In [53]:
B.reshape(10, -1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])