In [1]:
import numpy as np
from scipy import sparse

In [21]:
A = np.array([
    [0,0,0,1],
    [0,2,0,0],
    [3,1,0,1]
])

In [22]:
b = sparse.csr_matrix(A)

In [23]:
b.todense()

matrix([[0, 0, 0, 1],
        [0, 2, 0, 0],
        [3, 1, 0, 1]], dtype=int64)

In [24]:
b.data

array([1, 2, 3, 1, 1], dtype=int64)

In [25]:
b.shape

(3, 4)

In [26]:
b.indices

array([3, 1, 0, 1, 3], dtype=int32)

In [32]:
b.indptr

array([0, 1, 2, 5], dtype=int32)

In [42]:
c = sparse.csc_matrix((b.data, b.indices, b.indptr), shape=(4, 3))

In [43]:
c

<4x3 sparse matrix of type '<class 'numpy.int64'>'
	with 5 stored elements in Compressed Sparse Column format>

In [44]:
c.todense()

matrix([[0, 0, 3],
        [0, 2, 1],
        [0, 0, 0],
        [1, 0, 1]], dtype=int64)